"""
Created on Jun 5, 2023

@author: mning
"""


def getManFeatsFn() -> list:
    # just make it case insensitive
    return [
        "computeFOOOF_exponent_P1",
        "computeFOOOF_exponent_C3",
        "computeFOOOF_exponent_CPz",
        "computeFOOOF_exponent_CP2",
        "computeFOOOF_exponent_P2",
        "computeFOOOF_exponent_POz",
        "computeFOOOF_exponent_Pz",
        "computeFOOOF_exponent_Cz",
        "computeFOOOF_exponent_TP8",
        "computeFOOOF_exponent_C2",
        "computeFOOOF_exponent_PO4",
        "computeFOOOF_offset_P1",
        "computeFOOOF_offset_POz",
        "computeFOOOF_offset_PO4",
        "computeFOOOF_offset_Cz",
        "computeFOOOF_offset_Pz",
        "computeFOOOF_offset_CP1",
        "computeFOOOF_offset_P2",
        "computeFOOOF_offset_CPz",
        "computeFOOOF_offset_CP2",
        "computeFOOOF_offset_O2",
        "computeFOOOF_offset_PO8",
        "computeFOOOF_CF2_Fz",
        "computeFOOOF_CF2_F4",
        "computeFOOOF_CF2_F3",
        "computeFOOOF_CF2_Pz",
        "computeFOOOF_CF2_F1",
        "computeFOOOF_CF2_AF4",
        "computeFOOOF_CF2_T7",
        "computeFOOOF_CF2_CPz",
        "computeFOOOF_CF2_F5",
        "computeFOOOF_CF2_AF3",
        "computeFOOOF_CF2_FT7",
        "computeFOOOF_CF2_F7",
        "computeFOOOF_CF2_AF7",
        "computeFOOOF_CF2_FC6",
        "computeFOOOF_CF2_C1",
        "computeFOOOF_CF2_P5",
        "computeFOOOF_CF2_C3",
        "computeFOOOF_CF2_O1",
        "computeFOOOF_CF2_F8",
        "computeFOOOF_CF2_F6",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_Fp2",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_AF3",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_F4",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_FC6",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_P7",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_Fp1",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_CP1",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_FC4",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_AF4",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_F2",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_F5",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_AF7",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_CP4",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_CP5",
        "getMTSpectrogramSbj_alpha_spec_kurtosis_Fz",
        "getMTSpectrogramSbj_beta_spec_kurtosis_C3",
        "getMTSpectrogramSbj_beta_spec_kurtosis_C1",
        "getMTSpectrogramSbj_beta_spec_kurtosis_FC2",
        "getMTSpectrogramSbj_beta_spec_kurtosis_CP3",
        "getMTSpectrogramSbj_beta_spec_kurtosis_TP7",
        "getMTSpectrogramSbj_beta_spec_kurtosis_C5",
        "getMTSpectrogramSbj_beta_spec_kurtosis_FC6",
    ]
